let num1 = 2;
let num2 = 31;
let num3 = 25;
let num4 = 7;
let multiply = num1 * num2;
let random = Math.floor(Math.random() * 100) + 1;
console.log(random);  
let mod = num3 % num4;
console.log(mod);
let max = Math.max(1, 5, 10, 20, 3);
console.log(max);